require("custom.colors")
require("custom.globals")
require("custom.mappings")
require("custom.notes")
require("custom.settings")
require("custom.filetype")
require("custom.user-functions")
require("custom.link-following")
